name: memoize
version: 2.0.0
description: Returns cached result of function call when inputs were not changed from previous invocation.

authors:
- Alexander Polyankin <alexander.polyankin@team.wrike.com>
- Max Grebenschikov <maxim.grebenshikov@team.wrike.com>

homepage: https://github.com/wrike/memoize_dart

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dev_dependencies:
  test: '^1.0.0'
