name: memoize
version: 1.3.0
description: Returns cached result of function call when inputs were not changed from previous invocation.

authors:
- Alexander Polyankin <alexander.polyankin@team.wrike.com>
- Max Grebenschikov <maxim.grebenshikov@team.wrike.com>

homepage: https://github.com/wrike/memoize_dart

environment:
  sdk: '>=1.21.0 <2.0.0'

dependencies:
  func: ">=1.0.0 <2.0.0"

dev_dependencies:
  test: 0.12.24+2
